/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Cityscape.glb -t s 
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
 nodes: {
  Empty002: THREE.Mesh;
 };
 materials: {
  ["Empty.001"]: THREE.MeshStandardMaterial;
 };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
 const { nodes, materials } = useGLTF("/Cityscape.glb") as GLTFResult;
 return (
  <group {...props} dispose={null}>
   <mesh
    geometry={nodes.Empty002.geometry}
    material={materials["Empty.001"]}
    rotation={[Math.PI / 2, 0, -Math.PI / 2]}
   />
  </group>
 );
}

useGLTF.preload("/Cityscape.glb");
