/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Floor.glb -t s 
*/

import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
 nodes: {
  Plane: THREE.Mesh;
 };
 materials: {
  ["Wood Floor"]: THREE.MeshStandardMaterial;
 };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
 const { nodes, materials } = useGLTF("/Floor.glb") as GLTFResult;
 return (
  <group {...props} dispose={null}>
   <mesh
    geometry={nodes.Plane.geometry}
    material={materials["Wood Floor"]}
    scale={[1.804, 1, 4.302]}
   />
  </group>
 );
}

useGLTF.preload("/Floor.glb");
