/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Keyboard.glb -t s 
*/

import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
 nodes: {
  Plane082: THREE.Mesh;
  Plane082_1: THREE.Mesh;
  Plane082_2: THREE.Mesh;
  Plane082_3: THREE.Mesh;
  Plane082_4: THREE.Mesh;
 };
 materials: {
  PaletteMaterial002: THREE.MeshStandardMaterial;
  PaletteMaterial003: THREE.MeshPhysicalMaterial;
  PaletteMaterial005: THREE.MeshStandardMaterial;
  PaletteMaterial001: THREE.MeshStandardMaterial;
  PaletteMaterial004: THREE.MeshStandardMaterial;
 };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
 const { nodes, materials } = useGLTF("/Keyboard.glb") as GLTFResult;
 return (
  <group {...props} dispose={null}>
   <group
    position={[-1.381, 0.2, -0.055]}
    rotation={[0, -1.571, 0]}
    scale={[0.048, 0.061, 0.044]}
   >
    <mesh
     geometry={nodes.Plane082.geometry}
     material={materials.PaletteMaterial002}
    />
    <mesh
     geometry={nodes.Plane082_1.geometry}
     material={materials.PaletteMaterial003}
    />
    <mesh
     geometry={nodes.Plane082_2.geometry}
     material={materials.PaletteMaterial005}
    />
    <mesh
     geometry={nodes.Plane082_3.geometry}
     material={materials.PaletteMaterial001}
    />
    <mesh
     geometry={nodes.Plane082_4.geometry}
     material={materials.PaletteMaterial004}
    />
   </group>
  </group>
 );
}

useGLTF.preload("/Keyboard.glb");
