/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
 nodes: {
  Circle004: THREE.Mesh;
  Circle004_1: THREE.Mesh;
  Circle004_2: THREE.Mesh;
 };
 materials: {
  PaletteMaterial001: THREE.MeshStandardMaterial;
  PaletteMaterial002: THREE.MeshPhysicalMaterial;
  PaletteMaterial003: THREE.MeshStandardMaterial;
 };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
 const { nodes, materials } = useGLTF("/Monitors.glb") as GLTFResult;
 return (
  <group {...props} dispose={null}>
   <group position={[0, 0.234, 0]}>
    <mesh
     geometry={nodes.Circle004.geometry}
     material={materials.PaletteMaterial001}
    />
    <mesh
     geometry={nodes.Circle004_1.geometry}
     material={materials.PaletteMaterial002}
    />
    <mesh
     geometry={nodes.Circle004_2.geometry}
     material={materials.PaletteMaterial003}
    />
   </group>
  </group>
 );
}

useGLTF.preload("/Monitors.glb");
